// Code generated by "stringer -type=Method"; DO NOT EDIT.

package client

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[POST-1]
	_ = x[GET-2]
	_ = x[PUT-3]
	_ = x[PATCH-4]
	_ = x[DELETE-5]
}

const _Method_name = "POSTGETPUTPATCHDELETE"

var _Method_index = [...]uint8{0, 4, 7, 10, 15, 21}

func (i Method) String() string {
	i -= 1
	if i < 0 || i >= Method(len(_Method_index)-1) {
		return "Method(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _Method_name[_Method_index[i]:_Method_index[i+1]]
}
